name: mbot
version: 1.0
author: m
main: fr.m.mbot.Main
commands:

  discord:
    description: send discord message
    aliases: ds

  discordReload:
    description: reload the config.yml
    aliases: [dsrl,discordrl,dsreload]
